CREATE OR REFRESH LIVE TABLE silver_table_1

AS
SELECT
    date,
    COALESCE(open, 0) AS open,
    COALESCE(high, 0) AS high,
    COALESCE(low, 0) AS low,
    COALESCE(close, 0) AS close,
    COALESCE(volume, 0) AS volume,
    COALESCE(dividends, 0) AS dividends,
    COALESCE(stock_splits, 0) AS stock_splits,
    COALESCE(price_range, high - low) AS price_range,
    COALESCE(price_change, close - open) AS price_change,
    COALESCE(price_change_pct, 0) AS price_change_pct,
    COALESCE(sma_5, 0) AS sma_5,
    COALESCE(ema_5, 0) AS ema_5,
    COALESCE(sma_10, 0) AS sma_10,
    COALESCE(ema_10, 0) AS ema_10,
    COALESCE(sma_20, 0) AS sma_20,
    COALESCE(ema_20, 0) AS ema_20,
    COALESCE(sma_50, 0) AS sma_50,
    COALESCE(ema_50, 0) AS ema_50,
    COALESCE(sma_100, 0) AS sma_100,
    COALESCE(ema_100, 0) AS ema_100,
    COALESCE(sma_200, 0) AS sma_200,
    COALESCE(ema_200, 0) AS ema_200,
    COALESCE(volatility_5d, 0) AS volatility_5d,
    COALESCE(volatility_10d, 0) AS volatility_10d,
    COALESCE(volatility_20d, 0) AS volatility_20d,
    COALESCE(volatility_50d, 0) AS volatility_50d,
    COALESCE(rsi_14, 50) AS rsi_14,          
    COALESCE(macd, 0) AS macd,
    COALESCE(macd_signal, 0) AS macd_signal,
    COALESCE(macd_histogram, 0) AS macd_histogram,
    COALESCE(bb_middle, close) AS bb_middle,
    COALESCE(bb_upper, close) AS bb_upper,
    COALESCE(bb_lower, close) AS bb_lower,
    COALESCE(bb_width, 0) AS bb_width,
    COALESCE(volume_sma_20, 0) AS volume_sma_20,
    COALESCE(volume_ratio, 0) AS volume_ratio,
    COALESCE(return_1d, 0) AS return_1d,
    COALESCE(return_5d, 0) AS return_5d,
    COALESCE(return_10d, 0) AS return_10d,
    COALESCE(return_20d, 0) AS return_20d,
    COALESCE(return_60d, 0) AS return_60d,
    COALESCE(return_120d, 0) AS return_120d,
    COALESCE(return_252d, 0) AS return_252d,
    COALESCE(close_lag_1, close) AS close_lag_1,
    COALESCE(volume_lag_1, volume) AS volume_lag_1,
    COALESCE(close_lag_2, close) AS close_lag_2,
    COALESCE(volume_lag_2, volume) AS volume_lag_2,
    COALESCE(close_lag_3, close) AS close_lag_3,
    COALESCE(volume_lag_3, volume) AS volume_lag_3,
    COALESCE(close_lag_5, close) AS close_lag_5,
    COALESCE(volume_lag_5, volume) AS volume_lag_5,
    COALESCE(close_lag_10, close) AS close_lag_10,
    COALESCE(volume_lag_10, volume) AS volume_lag_10,
    COALESCE(target_return_1d, 0) AS target_return_1d,
    COALESCE(target_direction, 'Unknown') AS target_direction,
    year, month, day, dayofweek, quarter,
    is_month_start, is_month_end, is_quarter_start, is_quarter_end,
    fiscal_year, fiscal_quarter,
    COALESCE(price_range_mean, 0) AS price_range_mean,
    COALESCE(volatility_20d_mean, 0) AS volatility_20d_mean,
    COALESCE(rsi_14_mean, 50) AS rsi_14_mean,
    COALESCE(revenue_mac, 0) AS revenue_mac,
    COALESCE(revenue_services, 0) AS revenue_services,
    COALESCE(revenue_wearables_other, 0) AS revenue_wearables_other,
    COALESCE(revenue_ipad, 0) AS revenue_ipad,
    COALESCE(revenue_iphone, 0) AS revenue_iphone,
    COALESCE(revenue_total, 0) AS revenue_total,
   COALESCE(share_mac, 0) AS share_mac,
    COALESCE(share_services, 0) AS share_services,
    COALESCE(share_wearables_other, 0) AS share_wearables_other,
    COALESCE(share_ipad, 0) AS share_ipad,
    COALESCE(share_iphone, 0) AS share_iphone

FROM bronze_table_1;
